### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method '>' was called on null.

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#11]
I got this error: 

```
E/flutter ( 3068): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 3068): #1      WebSocketTransport.receive.<anonymous closure> (package:connectanum/src/transport/websocket/websocket_transport_io.dart:91:29)
```

Looks like this happens in this package line: 
`if (_socket.closeCode > 1000 && !_goodbyeSent && !_goodbyeReceived) { `

**Comment by andzejsw** [comment]
As i understand, by some reason `closeCode` is being `null`. And that leads to exception.
