### ISSUE TITLE
Implement CBOR serializer

### ISSUE THREAD

**Issue by om26er** [konsultaner/connectanum-dart#45]
Currently this library only implements json and msgpack serializers for WAMP. Would be good if CBOR was supported as well.

**Comment by konsultaner** [comment]
@om26er Thats true. I'll have a look if there is an easy way to implement it.

**Comment by konsultaner** [comment]
https://pub.dev/packages/cbor

There a dart lib supporting cbor

**Comment by om26er** [comment]
@konsultaner that library looks good enough. Hope we can have CBOR soonish. Ultimately I might be able to do that myself but that will likely be a few weeks once I get some time.

**Comment by konsultaner** [comment]
https://cbor.me/ to convert json from the json serioalizer tests to cbor
https://cryptii.com/pipes/integer-encoder to convert hex string to uint8list to test the deserializer

@om26er if I can't finish it soon, this is a good start:
https://github.com/konsultaner/connectanum-dart/blob/ee5d1c669cc6cabda62bc317948c13f4b3c3c5b9/test/serializer/cbor/serializer_test.dart

**Comment by konsultaner** [comment]
@om26er could you give the cbor serializer a try? I finished the implementation. Please checkout the `serializer_cbor` branch for this.

**Comment by konsultaner** [comment]
@oberstet do you see any chance to confirm that cbor serializer is working in production? My router doesn't speak cbor. This is only a unit test implementation.
@om26er maybe you get a chance to test it soon? Would like to deploy it.

**Comment by oberstet** [comment]
@konsultaner the product of the company Omer is working for is based on WAMP and would profit from this, so they are the right addressee ..

**Comment by om26er** [comment]
> @oberstet do you see any chance to confirm that cbor serializer is working in production? My router doesn't speak cbor. This is only a unit test implementation.
> @om26er maybe you get a chance to test it soon? Would like to deploy it.

Hey I'll try that today and update here

**Comment by imranhakeem** [comment]
@konsultaner I just gave this branch a try. I tried both Crossbar and Nexus and it seems it doesn't really work. Below are the logs I see in Crossbar
```
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] 
[('logOctets', False, 'WampWebSocketServerFactory'),
 ('logFrames', False, 'WampWebSocketServerFactory'),
 ('trackTimings', False, 'WampWebSocketServerFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketServerFactory'),
 ('applyMask', True, 'WampWebSocketServerFactory'),
 ('maxFramePayloadSize', 1048576, 'WampWebSocketServerFactory'),
 ('maxMessagePayloadSize', 1048576, 'WampWebSocketServerFactory'),
 ('autoFragmentSize', 65536, 'WampWebSocketServerFactory'),
 ('failByDrop', True, 'WampWebSocketServerFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketServerFactory'),
 ('openHandshakeTimeout', 2.5, 'WampWebSocketServerFactory'),
 ('closeHandshakeTimeout', 1, 'WampWebSocketServerFactory'),
 ('tcpNoDelay', True, 'WampWebSocketServerFactory'),
 ('autoPingInterval', 10.0, 'WampWebSocketServerFactory'),
 ('autoPingTimeout', 5.0, 'WampWebSocketServerFactory'),
 ('autoPingSize', 12, 'WampWebSocketServerFactory'),
 ('autoPingRestartOnAnyTraffic', True, 'WampWebSocketServerFactory'),
 ('versions', [8, 13], 'WampWebSocketServerFactory'),
 ('webStatus', False, 'WampWebSocketServerFactory'),
 ('requireMaskedClientFrames', True, 'WampWebSocketServerFactory'),
 ('maskServerFrames', False, 'WampWebSocketServerFactory'),
 ('perMessageCompressionAccept',
  <function set_websocket_options.<locals>.accept at 0x7ff5362bf4c0>,
  'WampWebSocketServerFactory'),
 ('serveFlashSocketPolicy', False, 'WampWebSocketServerFactory'),
 ('flashSocketPolicy',
  '<cross-domain-policy>\n'
  '     <allow-access-from domain="*" to-ports="*" />\n'
  '</cross-domain-policy>\x00',
  'WampWebSocketServerFactory'),
 ('allowedOrigins', ['*'], 'WampWebSocketServerFactory'),
 ('allowedOriginsPatterns', [re.compile('^.*$')], 'WampWebSocketServerFactory'),
 ('allowNullOrigin', True, 'WampWebSocketServerFactory'),
 ('maxConnections', 0, 'WampWebSocketServerFactory'),
 ('trustXForwardedFor', 0, 'WampWebSocketServerFactory')]
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] connection accepted from peer tcp4:127.0.0.1:39502
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Connection made to tcp4:127.0.0.1:39502
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] received HTTP request:

b'GET /ws HTTP/1.1\r\nUser-Agent: Dart/2.17 (dart:io)\r\nConnection: Upgrade\r\nCache-Control: no-cache\r\nAccept-Encoding: gzip\r\nSec-Websocket-Version: 13\r\nHost: 10.0.2.2:8080\r\nSec-Websocket-Extensions: permessage-deflate; client_max_window_bits\r\nSec-Websocket-Key: 6jYiJvsvvQHUp4Vzh6uTtw==\r\nSec-Websocket-Protocol: wamp.2.cbor\r\nUpgrade: websocket\r\n\r\n'


2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] received HTTP status line in opening handshake : GET /ws HTTP/1.1
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] received HTTP headers in opening handshake : {'user-agent': 'Dart/2.17 (dart:io)', 'connection': 'Upgrade', 'cache-control': 'no-cache', 'accept-encoding': 'gzip', 'sec-websocket-version': '13', 'host': '10.0.2.2:8080', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'sec-websocket-key': '6jYiJvsvvQHUp4Vzh6uTtw==', 'sec-websocket-protocol': 'wamp.2.cbor', 'upgrade': 'websocket'}
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] skipping opening handshake port checking - neither WS URL nor external port set
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Hybi protocol detected
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Cookie tracking disabled on WebSocket connection <crossbar.router.protocol.WampWebSocketServerProtocol object at 0x7ff5362c0460>
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] parsed WebSocket extension 'permessage-deflate' with params '{'client_max_window_bits': [True]}'
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] sending HTTP response:

HTTP/1.1 101 Switching Protocols
Server: Crossbar
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Protocol: wamp.2.cbor
Sec-WebSocket-Accept: 0/eumihzKZya56GdWE81HdBmSNk=
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits=13


2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] openHandshakeTimeoutCall.cancel
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.session.RouterSession] Client session connected - transport: {'type': 'websocket', 'protocol': 'wamp.2.cbor', 'peer': 'tcp4:127.0.0.1:39502', 'http_headers_received': {'user-agent': 'Dart/2.17 (dart:io)', 'connection': 'Upgrade', 'cache-control': 'no-cache', 'accept-encoding': 'gzip', 'sec-websocket-version': '13', 'host': '10.0.2.2:8080', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'sec-websocket-key': '6jYiJvsvvQHUp4Vzh6uTtw==', 'sec-websocket-protocol': 'wamp.2.cbor', 'upgrade': 'websocket'}, 'http_headers_sent': {}, 'websocket_extensions_in_use': [{'extension': 'permessage-deflate', 'is_server': True, 'server_no_context_takeover': False, 'client_no_context_takeover': False, 'server_max_window_bits': 13, 'client_max_window_bits': 13, 'mem_level': 5}], 'cbtid': None, 'channel_id': '0000000000000000000000000000000000000000000000000000000000000000'}
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] RX compressed [length]: octets
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Traceback (most recent call last):
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/serializer.py", line 278, in unserialize
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/serializer.py", line 768, in unserialize
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/serializer.py", line 280, in unserialize
autobahn.wamp.exception.ProtocolError: invalid serialization of WAMP message: MemoryError 

2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Failing WAMP-over-WebSocket transport: code=1002, reason="WAMP Protocol Error (invalid serialization of WAMP message: MemoryError )"
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] failing WebSocket connection (code=1002): "WAMP Protocol Error (invalid serialization of WAMP message: MemoryError )"
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] dropping connection to peer tcp4:127.0.0.1:39502 with abort=True: I dropped the WebSocket TCP connection: WAMP Protocol Error (invalid serialization of WAMP message: MemoryError )
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Connection to/from tcp4:127.0.0.1:39502 was aborted locally
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] _connectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionAborted'>: Connection was aborted locally using ITCPTransport.abortConnection.
]
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] Auto ping/pong: canceling autoPingPendingCall upon lost connection
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.protocol.WampWebSocketServerProtocol] WAMP-over-WebSocket transport lost: wasClean=False, code=1006, reason="connection was closed uncleanly (I dropped the WebSocket TCP connection: WAMP Protocol Error (invalid serialization of WAMP message: MemoryError ))"
2022-07-08T17:41:22+0500 [Router     110505 crossbar.router.session.RouterSession] RouterSession.onClose(was_clean=False)
```

**Comment by konsultaner** [comment]
@imranhakeem Did you also replace the `Serializer()` in your code? Just setting `WebSocketSerialization.SERIALIZATION_CBOR` is not enough. If you did change the `Serializer()` import, could you debug what message killed the serializer?

**Comment by imranhakeem** [comment]
@konsultaner you are right, I was importing the wrong file. However I did find out that a missing file for cbor, hence I created a PR https://github.com/konsultaner/connectanum-dart/pull/46

After the above change I am able to use CBOR, only did basic testing but I think this is good

**Comment by om26er** [comment]
@konsultaner I work with @imranhakeem, with the proposed change CBOR seems to work now

**Comment by konsultaner** [comment]
merged the branch
